[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=*, microphone=*, display-capture=*, geolocation=(), payment=(), usb=()"
    Feature-Policy = "camera 'self' https://meet.jit.si; microphone 'self' https://meet.jit.si; display-capture 'self' https://meet.jit.si"

[[headers]]
  for = "/meeting/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://meet.jit.si https://*.jitsi.net https://*.jitsi.org; style-src 'self' 'unsafe-inline' https://meet.jit.si https://*.jitsi.net; img-src 'self' data: https: blob:; media-src 'self' https: blob:; connect-src 'self' https: wss: blob:; font-src 'self' data: https:; frame-src 'self' https://meet.jit.si https://*.jitsi.net https://*.jitsi.org; worker-src 'self' blob:; child-src 'self' blob: https://meet.jit.si;"
