[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=*, microphone=*, display-capture=*, geolocation=(), payment=(), usb=()"

[[headers]]
  for = "/meeting/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: wss: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://meet.jit.si https://*.jitsi.net https://*.jitsi.org https://8x8.vc; style-src 'self' 'unsafe-inline' https://meet.jit.si https://*.jitsi.net https://fonts.googleapis.com; img-src 'self' data: https: blob:; media-src 'self' https: blob: mediastream:; connect-src 'self' https: wss: blob:; font-src 'self' data: https: https://fonts.gstatic.com; frame-src 'self' https://meet.jit.si https://*.jitsi.net https://*.jitsi.org https://8x8.vc; worker-src 'self' blob:; child-src 'self' blob: https://meet.jit.si https://*.jitsi.net;"
